//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRelationship
    {
        public int CompanyRelationshipId { get; set; }
        public Nullable<int> CompanyRelationshipTypeId { get; set; }
        public Nullable<int> FromCompany { get; set; }
        public Nullable<int> ToCompany { get; set; }
    
        public virtual GameCompany GameCompany { get; set; }
        public virtual GameCompany GameCompany1 { get; set; }
        public virtual CompanyRelationshipType CompanyRelationshipType { get; set; }
    }
}
