//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.DigtialGames = new HashSet<DigtialGame>();
        }
    
        public int GameId { get; set; }
        public int PlatformId { get; set; }
        public string Title { get; set; }
        public Nullable<int> DeveloperId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public Nullable<bool> HasCase { get; set; }
        public Nullable<bool> HasManual { get; set; }
        public string ModelName { get; set; }
        public Nullable<bool> HasAccessory { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
    
        public virtual GameCompany GameCompany { get; set; }
        public virtual GameCompany GameCompany1 { get; set; }
        public virtual GameOwner GameOwner { get; set; }
        public virtual GameRegion GameRegion { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual PhysicalGame PhysicalGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DigtialGame> DigtialGames { get; set; }
    }
}
