//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class NESView1
    {
        public int GameId { get; set; }
        public int PlatformId { get; set; }
        public string Title { get; set; }
        public Nullable<int> DeveloperId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public Nullable<bool> HasCase { get; set; }
        public Nullable<bool> HasManual { get; set; }
        public string ModelName { get; set; }
        public Nullable<bool> HasAccessory { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Notes { get; set; }
    }
}
