//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class WantedHardware
    {
        public int Id { get; set; }
        public string HardwareItemName { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> IdealPrice { get; set; }
        public Nullable<decimal> ExpectedPrice { get; set; }
    }
}
