SET IDENTITY_INSERT [dbo].[Platforms] ON
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (1, N'Super Nintendo Entertainment System', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (2, N'Nintendo Entertainment System', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (3, N'Game Boy', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (4, N'Game Boy Color', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (5, N'Game Boy Advance', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (6, N'Wii', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (7, N'Wii U', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (8, N'Gamecube', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (9, N'Nintendo DS', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (10, N'Nintendo 3DS', 1)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (11, N'Xbox', 3)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (12, N'Xbox 360', 3)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (13, N'PlayStation', 2)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (14, N'PlayStation 2', 2)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (15, N'PlayStation 3', 2)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (16, N'PlayStation 4', 2)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (17, N'PlayStation Portable', 2)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (18, N'Dreamcast', 5)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (19, N'Atari 2600', 6)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (20, N'Sega Genesis', 5)
INSERT INTO [dbo].[Platforms] ([PlatformId], [PlatformName], [CompanyId]) VALUES (21, N'ColecoVision', 7)
SET IDENTITY_INSERT [dbo].[Platforms] OFF
