SET IDENTITY_INSERT [dbo].[GameCompanies] ON
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (1, N'Nintendo')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2, N'Sony')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3, N'Microsoft')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (4, N'Capcom')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (5, N'Sega')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (6, N'Atari')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (7, N'Coleco Industries')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (8, N'SquareSoft')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (9, N'Jaleco')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (1008, N'Enix')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (1009, N'Konami')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (1010, N'Rare')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2008, N'Tengen')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2009, N'Sunsoft')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2010, N'Acclaim')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2011, N'Hudson Soft')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2012, N'Imagineering')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2013, N'Absolute Entertainment')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2014, N'Bally Midway')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2015, N'Data East')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2016, N'Beam Software')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2017, N'Tradewest')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2018, N'Micronics')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2019, N'Brøderbund')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2020, N'MicroGraphic Image')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2021, N'Bullet-Proof Software')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (2022, N'Aicom')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3008, N'Wayforward')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3009, N'Majesco')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3010, N'From Software')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3011, N'Ubisoft')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3012, N'Square Enix')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3013, N'Bandai')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3014, N'Namco')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3015, N'Namco Bandai')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3016, N'Ultimate Play The Game')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3017, N'DMA Design Limited')
INSERT INTO [dbo].[GameCompanies] ([GameCompanyId], [GameCompanyName]) VALUES (3018, N'Rockstar North')
SET IDENTITY_INSERT [dbo].[GameCompanies] OFF
